[project]
name = "mcp-ad-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.59.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.2",
    "requests>=2.32.4",
]
